add_test([=[GoogleTestCi.Foo]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=GoogleTestCi.Foo]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GoogleTestCi.Foo]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExampleTest.DmitriiLeonidovich]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=ExampleTest.DmitriiLeonidovich]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExampleTest.DmitriiLeonidovich]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.BasicConstructor]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.BasicConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.BasicConstructor]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.ConstructorWithParametr]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.ConstructorWithParametr]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.ConstructorWithParametr]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.InitializerList]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.InitializerList]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.InitializerList]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Output]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Output]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Output]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Subscript]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Subscript]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Subscript]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Determinant]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Determinant]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Determinant]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Transpose]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Transpose]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Transpose]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Multiplication]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Multiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Multiplication]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Addition]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Addition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Addition]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Substraction]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Substraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Substraction]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.GetMinor]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.GetMinor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.GetMinor]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Reverse]=]  /home/sonik/CLionProjects/matrix/mybuild/example_tests [==[--gtest_filter=MatrixTest.Reverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Reverse]=]  PROPERTIES WORKING_DIRECTORY /home/sonik/CLionProjects/matrix/mybuild SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  example_tests_TESTS GoogleTestCi.Foo ExampleTest.DmitriiLeonidovich MatrixTest.BasicConstructor MatrixTest.ConstructorWithParametr MatrixTest.InitializerList MatrixTest.Output MatrixTest.Subscript MatrixTest.Determinant MatrixTest.Transpose MatrixTest.Multiplication MatrixTest.Addition MatrixTest.Substraction MatrixTest.GetMinor MatrixTest.Reverse)
